name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install libjemalloc-dev
      run: sudo apt-get install libjemalloc-dev
          
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ./examples/assert
        ./examples/baseline_leak
        ./examples/baseline_undefined
        ./examples/bm_seed_address
        ./examples/custom_leak
        ./examples/indirect_undefined
        ./examples/l1d_miss_address
        ./examples/raw_thread
        ./examples/suspend
        ./examples/assert_address
        ./examples/baseline_multi
        ./examples/basic
        ./examples/bm_seed_leak
        ./examples/custom_thread
        ./examples/jemalloc
        ./examples/l1d_miss_leak
        ./examples/raw_undefined
        ./examples/suspend_address
        ./examples/assert_leak
        ./examples/baseline_multi_address
        ./examples/basic_address
        ./examples/bm_seed_thread
        ./examples/custom_undefined
        ./examples/jemalloc_address
        ./examples/l1d_miss_thread
        ./examples/storms
        ./examples/suspend_leak
        ./examples/assert_thread
        ./examples/baseline_multi_leak
        ./examples/basic_leak
        ./examples/bm_seed_undefined
        ./examples/indirect
        ./examples/jemalloc_leak
        ./examples/l1d_miss_undefined
        ./examples/storms_address
        ./examples/suspend_thread
        ./examples/assert_undefined
        ./examples/baseline_multi_thread
        ./examples/basic_thread
        ./examples/indirect_address
        ./examples/jemalloc_thread*
        ./examples/raw
        ./examples/storms_leak
        ./examples/suspend_undefined
        ./examples/baseline
        ./examples/baseline_multi_undefined
        ./examples/basic_undefined
        ./examples/custom
        ./examples/indirect_leak
        ./examples/jemalloc_undefined
        ./examples/raw_address
        ./examples/storms_thread
        ./examples/baseline_address
        ./examples/baseline_thread
        ./examples/bm_seed
        ./examples/custom_address
        ./examples/indirect_thread
        ./examples/l1d_miss
        ./examples/raw_leak
        ./examples/storms_undefined
        
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Install libjemalloc-dev
        run: sudo apt-get install libjemalloc-dev

      - uses: actions/checkout@v3
      
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Run benchmark (get data)
        working-directory: ${{github.workspace}}/build
        run: 
          make baseline && ./examples/baseline -j | tee benchmark_baseline.json &&
          make basic    && ./examples/basic    -j | tee benchmark_basic.json    &&
          make bm_seed  && ./examples/bm_seed  -j | tee benchmark_bm_seed.json  &&
          make custom   && ./examples/custom   -j | tee benchmark_custom.json   &&
          make indirect && ./examples/indirect -j | tee benchmark_indirect.json &&
          make jemallic && ./examples/jemalloc -j | tee benchmark_jemalloc.json &&
          make l1d_miss && ./examples/l1d_miss -j | tee benchmark_l1d_miss.json &&
          make raw      && ./examples/raw      -j | tee benchmark_raw.json      &&
          make raw      && ./examples/indirect -j | tee benchmark_indirect.json &&
          make suspend  && ./examples/suspend  -j | tee benchmark_supend.json 

      - name: Store benchmark result (baseline)
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: b63-baseline
          tool: 'customSmallerIsBetter'
          output-file-path: build/benchmark_baseline.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@FloydZ'
      
      
      - name: Store benchmark result (basic)
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: b63-basic
          tool: 'customSmallerIsBetter'
          output-file-path: build/benchmark_basic.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@FloydZ'

      - name: Store benchmark result (bm_seed)
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: b63-bm_seed
          tool: 'customSmallerIsBetter'
          output-file-path: build/benchmark_bm_seed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@FloydZ'

      - name: Store benchmark result (custom)
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: b63-custom
          tool: 'customSmallerIsBetter'
          output-file-path: build/benchmark_custom.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@FloydZ'

      - name: Store benchmark result (indirect)
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: b63-indirect
          tool: 'customSmallerIsBetter'
          output-file-path: build/benchmark_indirect.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@FloydZ'

      - name: Store benchmark result (jemalloc)
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: b63-jemalloc
          tool: 'customSmallerIsBetter'
          output-file-path: build/benchmark_jemalloc.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@FloydZ'

      - name: Store benchmark result (raw)
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: b63-raw
          tool: 'customSmallerIsBetter'
          output-file-path: build/benchmark_raw.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@FloydZ'

      - name: Store benchmark result (suspend)
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: b63-supend
          tool: 'customSmallerIsBetter'
          output-file-path: build/benchmark_supend.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@FloydZ'
